export const words_text = {
    // "adios": "ADIÓS",
    "a": "A",
    "b": "B",
    "c": "C",
    "bien": "BIEN",
    // "buenas_noches": "BUENAS NOCHES",
    // "buenas_tardes": "BUENAS TARDES",
    "buenos_dias": "BUENOS DÍAS",
    "como_estas": "COMO ESTÁS",
    // "disculpa": "DISCULPA",
    // "gracias": "GRACIAS",
    "hola": "HOLA",
    "mal": "MAL",
    // "mas_o_menos": "MAS O MENOS",
    // "me_ayudas": "ME AYUDAS",
    // "por_favor": "POR FAVOR",
}